---
title: "Terms of Use"
type: "exercise"
description: "Use methods to eliminate repetition and fulfill legal obligations in your program"
tags: "methods, return-values, parameters, arguments"
visibility: "public"
ignore:
- "terms_of_use.md"
